wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.22
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.2
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 3
      4: 3.9.2
      5: 0.10.22
      8:
      - 5
